### ISSUE TITLE
Set up meetup group

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/meetups#1]
As part of our pitch for the 2019 meetup, we requested funds to run a meetup group, to mark this as done:

- [x] register/pay for meetup
- [x] set up description and url --> prelim: https://www.meetup.com/p2p-and-dweb-toronto/
- [x] invite fellow our networks organizers! (email!)
- [x] add photo/profile/link to website
- [x] get review on language
- [x] add first event

**Comment by patcon** [comment]
Maybe add a todo for adding this to a new yearly budget so it's accounted for before closure? Happy to kickstart a new budget myself (copying from [2018](https://docs.google.com/spreadsheets/d/108sbmdcf9ekxYRL3mpa1QBtmjhA5KwoO5w_XWtQgDS4/edit?usp=drive_web&ouid=117169981156567015860)) from $14.99/month (plus tax?) onward from Jan 9th :)

https://www.meetup.com/pricing/

**Comment by dcwalk** [comment]
@patcon -- sorry for not responding to this comment! We have this accounted for in the 2019 budget, my plan was to play in 6 month increments -- first one charged and next one coming up this summer :)
