### ISSUE TITLE
Livestreaming setup

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/meetups#15]
We've discussed livestreaming the invited presentation portion of the event, had a chat with @patcon and here is how Civic Tech does it, with the offer that we jump on Civic Tech Slack for help

- Equipment list
  - Laptop
  - Phone as backup camera
- [Civic Tech Runsheet](https://docs.google.com/document/d/1hbkZArGYcE1rI8_7QoRavMtWmqts4A7a1sdHxXq-aXQ/edit#)

**Comment by dcwalk** [comment]
A bit of an open question how we want to integrate with IPFS set up, my preference would be a first attempt at the flow with youtube before extending to also include IPFS

ping @benhylau

**Comment by benhylau** [comment]
https://github.com/ournetworks/meetups/pull/17
