### ISSUE TITLE
outreach to other p2p/dweb/decentralization groups in Toronto

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/meetups#4]
We should reach out to other p2p/dweb folks in Toronto!

**Comment by patcon** [comment]
Ah, was discussing something related on meetup, and migrated to Twitter:
https://www.meetup.com/p2p-and-dweb-toronto/discussions/6076485643403264/chat

(Very generally using "other decentralization groups" to mean, anyone interested to organized in less hierarchical fashion 😉 )
